package com.kinth.football.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CHAT.
 */
public class Chat {

    private Long id;
    private String conversationid;
    private String belongaccount;
    private String belongnick;
    private String belongavatar;
    /** Not-null value. */
    private String content;
    /** Not-null value. */
    private String belongid;
    private Integer status;
    private Integer msgtype;
    private String msgtime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Chat() {
    }

    public Chat(Long id) {
        this.id = id;
    }

    public Chat(Long id, String conversationid, String belongaccount, String belongnick, String belongavatar, String content, String belongid, Integer status, Integer msgtype, String msgtime) {
        this.id = id;
        this.conversationid = conversationid;
        this.belongaccount = belongaccount;
        this.belongnick = belongnick;
        this.belongavatar = belongavatar;
        this.content = content;
        this.belongid = belongid;
        this.status = status;
        this.msgtype = msgtype;
        this.msgtime = msgtime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getConversationid() {
        return conversationid;
    }

    public void setConversationid(String conversationid) {
        this.conversationid = conversationid;
    }

    public String getBelongaccount() {
        return belongaccount;
    }

    public void setBelongaccount(String belongaccount) {
        this.belongaccount = belongaccount;
    }

    public String getBelongnick() {
        return belongnick;
    }

    public void setBelongnick(String belongnick) {
        this.belongnick = belongnick;
    }

    public String getBelongavatar() {
        return belongavatar;
    }

    public void setBelongavatar(String belongavatar) {
        this.belongavatar = belongavatar;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    /** Not-null value. */
    public String getBelongid() {
        return belongid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBelongid(String belongid) {
        this.belongid = belongid;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getMsgtype() {
        return msgtype;
    }

    public void setMsgtype(Integer msgtype) {
        this.msgtype = msgtype;
    }

    public String getMsgtime() {
        return msgtime;
    }

    public void setMsgtime(String msgtime) {
        this.msgtime = msgtime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
