package com.kinth.football.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table COMMENT_DB.
 */
public class CommentDB implements Parcelable {

    /** Not-null value. */
    private String uuid;
    private String replyToPlayerUuid;
    private String sharingUuid;
    private String type;
    private String comment;
    private String playerUuid;
    private Long date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CommentDB() {
    }

    public CommentDB(String uuid) {
        this.uuid = uuid;
    }

    public CommentDB(String uuid, String replyToPlayerUuid, String sharingUuid, String type, String comment, String playerUuid, Long date) {
        this.uuid = uuid;
        this.replyToPlayerUuid = replyToPlayerUuid;
        this.sharingUuid = sharingUuid;
        this.type = type;
        this.comment = comment;
        this.playerUuid = playerUuid;
        this.date = date;
    }

    /** Not-null value. */
    public String getUuid() {
        return uuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getReplyToPlayerUuid() {
        return replyToPlayerUuid;
    }

    public void setReplyToPlayerUuid(String replyToPlayerUuid) {
        this.replyToPlayerUuid = replyToPlayerUuid;
    }

    public String getSharingUuid() {
        return sharingUuid;
    }

    public void setSharingUuid(String sharingUuid) {
        this.sharingUuid = sharingUuid;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getPlayerUuid() {
        return playerUuid;
    }

    public void setPlayerUuid(String playerUuid) {
        this.playerUuid = playerUuid;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    public static final Parcelable.Creator<CommentDB> CREATOR = new Creator<CommentDB>() {
		
		@Override
		public CommentDB[] newArray(int size) {
			return new CommentDB[size];
		}
		
		@Override
		public CommentDB createFromParcel(Parcel source) {
			CommentDB commentDB = new CommentDB();
			commentDB.uuid = source.readString();
			commentDB.replyToPlayerUuid = source.readString();
			commentDB.sharingUuid = source.readString();
			commentDB.type = source.readString();
			commentDB.comment = source.readString();
			commentDB.playerUuid = source.readString();
			commentDB.date = source.readLong();
			return commentDB;
		}
	};
	@Override
	public int describeContents() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeString(this.uuid);
		dest.writeString(this.replyToPlayerUuid);
		dest.writeString(this.sharingUuid);
		dest.writeString(this.type);
		dest.writeString(this.comment);
		dest.writeString(this.playerUuid);
		dest.writeLong(this.date == null ? 0l : this.date);
	}
    // KEEP METHODS END

}
