package com.kinth.football.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MATCH_TEAM_PLAYER.
 */
public class MatchTeamPlayer {

    private Long id;
    /** Not-null value. */
    private String player_id;
    private long match_team_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MatchTeamPlayer() {
    }

    public MatchTeamPlayer(Long id) {
        this.id = id;
    }

    public MatchTeamPlayer(Long id, String player_id, long match_team_id) {
        this.id = id;
        this.player_id = player_id;
        this.match_team_id = match_team_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPlayer_id() {
        return player_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlayer_id(String player_id) {
        this.player_id = player_id;
    }

    public long getMatch_team_id() {
        return match_team_id;
    }

    public void setMatch_team_id(long match_team_id) {
        this.match_team_id = match_team_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
