package com.kinth.football.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PUSH_MESSAGE.
 */
public class PushMessage {

    private Long id;
    /** Not-null value. */
    private String type;
    private Long date;
    private String content;
    private Boolean hasRead;
    private Integer isClick;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PushMessage() {
    }

    public PushMessage(Long id) {
        this.id = id;
    }

    public PushMessage(Long id, String type, Long date, String content, Boolean hasRead, Integer isClick) {
        this.id = id;
        this.type = type;
        this.date = date;
        this.content = content;
        this.hasRead = hasRead;
        this.isClick = isClick;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Boolean getHasRead() {
        return hasRead;
    }

    public void setHasRead(Boolean hasRead) {
        this.hasRead = hasRead;
    }

    public Integer getIsClick() {
        return isClick;
    }

    public void setIsClick(Integer isClick) {
        this.isClick = isClick;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
