package com.kinth.football.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table RECENT.
 */
public class Recent {

    private Long id;
    private String tuid;
    private String tusername;
    private String tnick;
    private String tavatar;
    /** Not-null value. */
    private String lastmessage;
    private Integer msgtype;
    private String msgtime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Recent() {
    }

    public Recent(Long id) {
        this.id = id;
    }

    public Recent(Long id, String tuid, String tusername, String tnick, String tavatar, String lastmessage, Integer msgtype, String msgtime) {
        this.id = id;
        this.tuid = tuid;
        this.tusername = tusername;
        this.tnick = tnick;
        this.tavatar = tavatar;
        this.lastmessage = lastmessage;
        this.msgtype = msgtype;
        this.msgtime = msgtime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTuid() {
        return tuid;
    }

    public void setTuid(String tuid) {
        this.tuid = tuid;
    }

    public String getTusername() {
        return tusername;
    }

    public void setTusername(String tusername) {
        this.tusername = tusername;
    }

    public String getTnick() {
        return tnick;
    }

    public void setTnick(String tnick) {
        this.tnick = tnick;
    }

    public String getTavatar() {
        return tavatar;
    }

    public void setTavatar(String tavatar) {
        this.tavatar = tavatar;
    }

    /** Not-null value. */
    public String getLastmessage() {
        return lastmessage;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLastmessage(String lastmessage) {
        this.lastmessage = lastmessage;
    }

    public Integer getMsgtype() {
        return msgtype;
    }

    public void setMsgtype(Integer msgtype) {
        this.msgtype = msgtype;
    }

    public String getMsgtime() {
        return msgtime;
    }

    public void setMsgtime(String msgtime) {
        this.msgtime = msgtime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
