package com.kinth.football.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table SHARING_DB.
 */
public class SharingDB implements Parcelable {

    /** Not-null value. */
    private String uuid;
    private Long date;
    private String type;
    private String comment;
    private String url;
    private String imageUrls;
    private String playerUuid;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SharingDB() {
    }

    public SharingDB(String uuid) {
        this.uuid = uuid;
    }

    public SharingDB(String uuid, Long date, String type, String comment, String url, String imageUrls, String playerUuid) {
        this.uuid = uuid;
        this.date = date;
        this.type = type;
        this.comment = comment;
        this.url = url;
        this.imageUrls = imageUrls;
        this.playerUuid = playerUuid;
    }

    /** Not-null value. */
    public String getUuid() {
        return uuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImageUrls() {
        return imageUrls;
    }

    public void setImageUrls(String imageUrls) {
        this.imageUrls = imageUrls;
    }

    public String getPlayerUuid() {
        return playerUuid;
    }

    public void setPlayerUuid(String playerUuid) {
        this.playerUuid = playerUuid;
    }

    // KEEP METHODS - put your custom methods here
    public static final Parcelable.Creator<SharingDB> CREATOR = new Creator<SharingDB>() {

		@Override
		public SharingDB createFromParcel(Parcel source) {
			SharingDB sharingDB = new SharingDB();
			sharingDB.uuid = source.readString();
			sharingDB.date = source.readLong();
			sharingDB.type = source.readString();
			sharingDB.comment = source.readString();
			sharingDB.url = source.readString();
			sharingDB.imageUrls = source.readString();
			sharingDB.playerUuid = source.readString();
			return sharingDB;
		}

		@Override
		public SharingDB[] newArray(int size) {
			// TODO Auto-generated method stub
			return new SharingDB[size];
		}
	};
	@Override
	public int describeContents() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeString(this.uuid);
		dest.writeLong(this.date == null ? 0l : this.date);
		dest.writeString(this.type);
		dest.writeString(this.comment);
		dest.writeString(this.url);
		dest.writeString(this.imageUrls);
		dest.writeString(this.playerUuid);
	}
    // KEEP METHODS END

}
