package com.kinth.football.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TEAM_PLAYER.
 */
public class TeamPlayer {

    private Long id;
    /** Not-null value. */
    private String player_id;
    /** Not-null value. */
    private String team_id;
    private Boolean creator;
    private String type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TeamPlayer() {
    }

    public TeamPlayer(Long id) {
        this.id = id;
    }

    public TeamPlayer(Long id, String player_id, String team_id, Boolean creator, String type) {
        this.id = id;
        this.player_id = player_id;
        this.team_id = team_id;
        this.creator = creator;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPlayer_id() {
        return player_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlayer_id(String player_id) {
        this.player_id = player_id;
    }

    /** Not-null value. */
    public String getTeam_id() {
        return team_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTeam_id(String team_id) {
        this.team_id = team_id;
    }

    public Boolean getCreator() {
        return creator;
    }

    public void setCreator(Boolean creator) {
        this.creator = creator;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
