package com.kinth.football.config;

/**
 * Action常量
 * 
 * @author Sola
 * 
 */
public class Action {

	// 比赛邀请
	public static final String ACTION_BROADCAST_MATCH_INVITATION = "ACTION_BROADCAST_MATCH_INVITATION";
	// 比赛确认
	public static final String ACTION_BROADCAST_MATCH_INVITATION_CONFIRM = "ACTION_BROADCAST_MATCH_INVITATION_CONFIRM";
	// 创建成功，开始报名
	public static final String ACTION_BROADCAST_MATCH_CREATED = "ACTION_BROADCAST_MATCH_CREATED";
	// 有人报名
	public static final String ACTION_BROADCAST_MATCH_SIGNUP = "ACTION_BROADCAST_MATCH_SIGNUP";
	// 待开赛
	public static final String ACTION_BROADCAST_MATCH_PENDING = "ACTION_BROADCAST_MATCH_PENDING";
	// 比赛中
	public static final String ACTION_BROADCAST_MATCH_KICK_OFF = "ACTION_BROADCAST_MATCH_KICK_OFF";
	// 待评价--比赛结束
	public static final String ACTION_BROADCAST_MATCH_OVER = "ACTION_BROADCAST_MATCH_OVER";
//	// 比赛关闭-评价完成后
//	public static final String ACTION_BROADCAST_MATCH_FINISHED = "ACTION_BROADCAST_MATCH_FINISHED";
	// 比赛取消
	public static final String ACTION_BROADCAST_MATCH_CANCELED = "ACTION_BROADCAST_MATCH_CANCELED";
	// 裁判邀请消息
	public static final String ACTION_BROADCAST_MATCH_REFEREE_INVITATION = "ACTION_BROADCAST_MATCH_REFEREE_INVITATION";
	// 约赛应战消息
	public static final String ACTION_BROADCAST_MATCH_CHALLENGE = "ACTION_BROADCAST_MATCH_CHALLENGE";
	// 约赛拒绝应战消息
	public static final String ACTION_BROADCAST_MATCH_CHALLENGE_CONFIRM = "ACTION_BROADCAST_MATCH_CHALLENGE_CONFIRM";
	// 比赛开赛前通知消息
	public static final String ACTION_BROADCAST_MATCH_KICK_OFF_NOTIFICATION = "ACTION_BROADCAST_MATCH_KICK_OFF_NOTIFICATION";
	// 裁判录入比分后推送给裁判
	public static final String ACTION_BROADCAST_MATCH_OVER_TO_REFEREE_NOTIFICATION = "ACTION_BROADCAST_MATCH_OVER_TO_REFEREE_NOTIFICATION";
	
	// 队长同意或者拒绝的消息
	public static final String ACTION_BROADCAST_MATCH_COMFIRM_OR_REFUSE = "ACTION_BROADCAST_MATCH_COMFIRM_OR_REFUSE";

}
